In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# import tensorflow as tf
# from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
from PIL import Image
import os

def preprocess_image(image_name):
    image_path = os.path.join('patch_images', image_name)  # Update the path to the images directory
    image = Image.open(image_path)
    image = image.resize((224, 224))
    image = np.array(image)
    image = image / 255.0
    return image





# Load the dataset

import io
main_data = pd.read_csv('data_labels_mainData.csv')
extra_data = pd.read_csv('data_labels_extraData.csv')


# Preprocess the data
# Load the additional dataset

# Preprocess the additional data
extra_data["isCancerous"] = np.where(extra_data["isCancerous"] == 0, 0, 1)

extra_images = np.array([preprocess_image(image_name) for image_name in extra_data["ImageName"]])
extra_labels = np.array(extra_data["isCancerous"])

In [13]:
print(extra_images)

[[[[0.65098039 0.49411765 0.70980392]
   [0.65098039 0.49411765 0.70980392]
   [0.64705882 0.49019608 0.70980392]
   ...
   [0.96470588 0.91372549 0.96470588]
   [0.95686275 0.91372549 0.96078431]
   [0.95686275 0.91372549 0.96078431]]

  [[0.65098039 0.49411765 0.70980392]
   [0.65098039 0.49411765 0.70980392]
   [0.64705882 0.49019608 0.70980392]
   ...
   [0.96470588 0.91372549 0.96470588]
   [0.95686275 0.91372549 0.96078431]
   [0.95686275 0.91372549 0.96078431]]

  [[0.65098039 0.49411765 0.70980392]
   [0.65098039 0.49411765 0.70980392]
   [0.64705882 0.49019608 0.70980392]
   ...
   [0.96078431 0.91372549 0.96470588]
   [0.95686275 0.91372549 0.96078431]
   [0.95686275 0.91372549 0.96078431]]

  ...

  [[0.46666667 0.29019608 0.58823529]
   [0.4627451  0.29019608 0.58431373]
   [0.46666667 0.29019608 0.58431373]
   ...
   [0.66666667 0.48627451 0.75294118]
   [0.66666667 0.48627451 0.75686275]
   [0.66666667 0.48627451 0.75686275]]

  [[0.46666667 0.29019608 0.58823529]
   [0.4